CREATE TABLE usuarios (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome  VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    role  VARCHAR(20)  NOT NULL,
    CONSTRAINT pk_usuarios PRIMARY KEY (id),
    CONSTRAINT uk_usuarios_email UNIQUE (email),
    CONSTRAINT ck_usuarios_role CHECK (role IN ('CLIENTE', 'ADMIN'))
);

CREATE TABLE pedidos (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id   BIGINT         NOT NULL,
    status       VARCHAR(30)    NOT NULL,
    data_criacao TIMESTAMP(6)   NOT NULL,
    valor_total  NUMERIC(12, 2) NOT NULL,
    CONSTRAINT pk_pedidos PRIMARY KEY (id),
    CONSTRAINT fk_pedidos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT ck_pedidos_status CHECK (status IN
        ('AGUARDANDO_PAGAMENTO', 'PAGO', 'EM_SEPARACAO', 'ENVIADO', 'ENTREGUE', 'CANCELADO'))
);

CREATE TABLE itens_pedido (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    pedido_id      BIGINT         NOT NULL,
    nome_produto   VARCHAR(150)   NOT NULL,
    quantidade     INTEGER        NOT NULL,
    preco_unitario NUMERIC(12, 2) NOT NULL,
    CONSTRAINT pk_itens_pedido PRIMARY KEY (id),
    CONSTRAINT fk_itens_pedido_pedido FOREIGN KEY (pedido_id) REFERENCES pedidos (id)
);

CREATE TABLE mensagens_chat (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id  BIGINT       NOT NULL,
    pergunta    TEXT         NOT NULL,
    resposta    TEXT,
    "timestamp" TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_mensagens_chat PRIMARY KEY (id),
    CONSTRAINT fk_mensagens_chat_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);
